All: multiplication fibonacci

multiplication: multiplication.s
	gcc multiplication.s -g -c -o multiplication.o
	gcc multiplication.o -g -o multiplication

fibonacci: fibonacci.s
	gcc fibonacci.s -g -c -o fibonacci.o
	gcc fibonacci.o -g -o fibonacci

clean: rm multiplication fibonacci
