All: 1_CelciusToFahrenheit 1_FahrenheitToCelcius 2_Negate 3_FeetToInches 3_InchesToFeet 4_Times10 ExtraCredit_Swap

1_CelciusToFahrenheit: 1_CelciusToFahrenheit.s
	gcc 1_CelciusToFahrenheit.s -g -c -o 1_CelciusToFahrenheit.o
	gcc 1_CelciusToFahrenheit.o -g -o 1_CelciusToFahrenheit

1_FahrenheitToCelcius: 1_FahrenheitToCelcius.s
	gcc 1_FahrenheitToCelcius.s -g -c -o 1_FahrenheitToCelcius.o
	gcc 1_FahrenheitToCelcius.o -g -o 1_FahrenheitToCelcius

2_Negate: 2_Negate.s
	gcc 2_Negate.s -g -c -o 2_Negate.o
	gcc 2_Negate.o -g -o 2_Negate

3_FeetToInches: 3_FeetToInches.s
	gcc 3_FeetToInches.s -g -c -o 3_FeetToInches.o
	gcc 3_FeetToInches.o -g -o 3_FeetToInches

3_InchesToFeet: 3_InchesToFeet.s
	gcc 3_InchesToFeet.s -g -c -o 3_InchesToFeet.o
	gcc 3_InchesToFeet.o -g -o 3_InchesToFeet

4_Times10: 4_Times10.s
	gcc 4_Times10.s -g -c -o 4_Times10.o
	gcc 4_Times10.o -g -o 4_Times10

ExtraCredit_Swap: ExtraCredit_Swap.s
	gcc ExtraCredit_Swap.s -g -c -o ExtraCredit_Swap.o
	gcc ExtraCredit_Swap.o -g -o ExtraCredit_Swap

clean: rm 1_CelciusToFahrenheit 1_FahrenheitToCelcius 2_Negate 3_FeetToInches 3_InchesToFeet 4_Times10 ExtraCredit_Swap
